
% First make sure that the updated version of your framework is copied 
% to the cluster.

%A) Specifying path dependencies in th esubmission script

% sched = findResource('scheduler','Configuration','HERO');
% 
% jobRW =...
%    batch(...
%         sched,...    
%         'test',...
%         'matlabpool',2,...
%         'PathDependencies',{'/user/fk5/ifp/agmediphys/wuau6202/MATLAB/R2015b/JobData/Uncertainty/'}...
%         );
    
%B) Specifying path dependencies in the matlab file (look if the line with
%path is added at the beginning of 'test.m') and then : 

% sched = parcluster('scheduler','Configuration','HERO');
defaultProfile = parallel.defaultClusterProfile;
myCluster = parcluster(defaultProfile);
% parpool(myCluster);

%set(myCluster, 'CommunicatingSubmitFcn', cat(2,myCluster.CommunicatingSubmitFcn,'memory','4G'));

jobRW =...
   batch(...
        myCluster,...    
        'producing_uncert_curves',...
        'pool',10 ...
        );
  